#!/usr/bin/bash

current() {
	ps -C swaybg -o args | sed -n 's/.* -i \(.*\.[^. ]\+\).*/\1/p'
}

STATE_FILE=$HOME/.local/state/custombg
BG_DIR=$HOME/Pictures/screen

pick() {
	local current=$(current) pick dir
	[[ $DIRECTION == prev* ]] && dir=(-B head) || dir=(-A tail)

	if [[ -z $current && ! -f $STATE_FILE ]]; then # initiate sequence
		pick=("$BG_DIR"/*)
	else # move to next image
		if [[ -z $current && -f ${current:=$(<"$STATE_FILE")} ]]; then
			echo "$current" # use the last saved image
			return
		fi # pick next bg closest in name

		current=${current##*/}
		pick=$BG_DIR/$({
			echo "$current"
			ls "$BG_DIR"
		} | sort | grep -F "$current" ${dir[0]} $((SKIP + 1)) | ${dir[1]} -n 1)

		if [[ ${pick##*/} == "$current" ]]; then
			pick=("$BG_DIR"/*) # reached last -> start from first
			[[ $DIRECTION == prev* ]] && pick=${pick[-1]}
		fi
	fi

	echo "$pick"
}

set() {
	if [[ $1 ]]; then
		[[ $1 == /* ]] && bg=$1 || bg="$PWD/$1"
	else
		bg=$(pick)
	fi

	killall swaybg &>/dev/null
	# swaymsg output '*' bg "$bg" fill
	swaymsg exec "swaybg -i $bg -m fill &>/dev/null"
}

save() {
	[[ -f $1 ]] && toSave=$1 || toSave=$(pick)
	[[ $toSave == $(<"$STATE_FILE") ]] || echo "$toSave" >"$STATE_FILE"
}

cursave() {
	save "$(current)"
}

autosave() {
	return # disable autosave for now
	hour=$(date +%H)
	if ((${hour#0} > 20)); then
		save
	fi
}

if declare -f "$1" &>/dev/null; then
	$1
else
	if [[ $1 == next || $1 == prev* ]]; then
		DIRECTION=$1
		shift
	fi

	set "$@"
fi
