#!/usr/bin/bash
# launch or focus based on $2=sway condition string
[[ $2 == *title* ]] || verify=" title=__focused__"
[[ $2 == *workspace* ]] || verify+=" workspace=__focused__"
if swaymsg "${2::-1} $verify]" focus || ! swaymsg "$2" focus; then
	swaymsg exec "$1" && while ! swaymsg "$2" focus; do sleep 0.2; done
fi
