#!/usr/bin/bash

current() {
	ps -C swaybg -o args | sed -n 's/.* -i \(.*\.[jJ][pP][gG]\).*/\1/p'
}

STATE_FILE=$HOME/.local/state/nextbg
BG_DIR=$HOME/Pictures/screen

next() {
	local current=${current:-$(current)}
	if [[ $current ]]; then # move to next image
		local next=$BG_DIR/$(ls "$BG_DIR" | grep -F "${current##*/}" -A 1 | tail -n 1)
		[[ $next == $current ]] && next=("$BG_DIR"/*) # reached last -> start from first
	fi

	[[ $next ]] && echo "$next" || cat "$STATE_FILE"
}

if [[ $1 == save ]]; then
	hour=$(date +%H)
	if ((${hour#0} > 20)); then
		current=$(current)
		[[ $current ]] && next >"$STATE_FILE"
	fi
elif [[ $1 == current ]]; then
	current
else
	if [[ $1 ]]; then
		[[ $1 == /* ]] && bg=$1 || bg="$PWD/$1"
	else
		bg=$(next)
	fi

	killall swaybg 2>/dev/null
	swaybg -i "$bg" -m fill &
fi
