#!/usr/bin/bash

current() {
	ps -C swaybg -o args | sed -n 's/.* -i \(.*\.[jJ][pP][gG]\).*/\1/p'
}

STATE_FILE="$HOME/.local/state/nextbg"

next() {
	local current=${current:-$(current)}
	if [[ $current ]]; then # find next item in CWD
		local next=$(ls | grep "$current" -A 1 | tail -n 1)
		[[ $next == $current ]] && next=(*) # reached last -> start from first
	fi

	[[ $next ]] && echo "$next" || cat "$STATE_FILE"
}

cd ~/Pictures/screen
if [[ $1 == save ]]; then
	hr=$(date +%H)
	if ((${hr#0} > 20)); then
		current=$(current)
		[[ $current ]] && next >"$STATE_FILE"
	fi
elif [[ $1 == current ]]; then
	current
else
	bg=$(next)

	killall swaybg 2>/dev/null
	swaybg -i "${bg:=$1}" -m fill &
fi
