#!/usr/bin/bash

if [[ -d $REPORT_TO ]]; then
	rep=${REPORT_TO}/workreport.md
elif [[ -z $REPORT_TO ]]; then
	echo 'REPORT_TO variable is not set'
	exit 1
else
	rep=$REPORT_TO
fi

TERM_DAY=$(head -n 1 "$rep")
if [[ $TERM_DAY =~ ^TERM_DAY=([1-9][0-9]*)$ ]]; then
	declare -i TERM_DAY=${BASH_REMATCH[1]}
else
	echo "'TERM_DAY=xx' must be the first line in the report file to identify the sum-up period in the month"
	exit 1
fi
# TODO: allow sum count to a specific date, currently 18

# sums time since last match of SEP_COND (separator awk condition)
splitTimes() {
	sed 's/^[^=]*= \([0-9.]\+\)/= \1/;s/;[^=]*= \([0-9.]\+\)/\n= \1/g' "$rep"
}
sumLast() {
	splitTimes | awk "$SEP_COND"' {x=0}; /^=/  {x+=$2}; END {print x}'
}
sumWeek() {
	SEP_COND='/^- W/' sumLast
}

sumTerm() {
	SEP_COND='/^- T/' sumLast
}

last=(
	$(awk '/^[0-9]/ {m=$1}; /^ *- [0-9]/ {d=$2}; END{print m" "d}' "$rep")
)
last[0]=${last[0]%.}
last[1]=${last[1]%.}
declare -ai new=($(date +"%m %d"))

isNewWeek() {
	declare -i yearLast=$(date +%Y)
	((new < last)) && yearLast+=-1
	local lastWeek=$(date -d "$year-${last[0]}-${last[1]}" +%W)
	lastWeek=${lastWeek#0}
	declare -i newWeek=$(date +%W)
	if ((lastWeek != 0 || newWeek != 52)); then # date treats leftover days in January as 0th week
		((newWeek != lastWeek))
	fi
}

isNewTerm() {
	((new < last)) && local new=($((new[0] + 12)) ${new[1]})
	if ((new > last)); then
		((new > last + 1 || last[1] < TERM_DAY || new[1] >= TERM_DAY))
	else
		((last[1] < TERM_DAY && new[1] >= TERM_DAY))
	fi
}

runAndTime() {
	start=$(date +%H:%M)
	"$@"
	((SECONDS < 60)) && exit
	dur="$start-$(date +%H:%M) = $(bc <<<"scale=2;$SECONDS/3600")"

	if ((last[0] == new[0] && last[1] == new[1])); then # append to current day
		head -n -1 "$rep" >/tmp/wrep
		echo "${last[1]}.; $dur" >>/tmp/wrep
		mv /tmp/wrep "$rep"
	else

		isNewWeek "${new[@]}" && echo "- W$(date +%W): $(sumWeek)" >>"$rep"
		isNewTerm "${new[@]}" && echo "- T${new}: $(sumTerm)" >>"$rep"
		((last != new)) && echo "${new}." >>"$rep" # mark beginning of current month

		echo "  - ${new[1]}. $dur" >>"$rep" # add time for new day
	fi
}

case "$1" in
	all) SEP_COND='0' sumLast ;;
	week) sumWeek ;;
	term) sumTerm ;;
	*) runAndTime "$@" ;;
esac
