declare -gA resizePresets
resizePresets['i=92/1.jxl']=resizeIdentity
resizePresets['h=90/2.jpg']=resizeHalf
resizePresets['m=85/2.jxl']=resizeMid
resizePresets['q=85/4.jxl']=resizeQuarter
resizePresets['l=82/1280.jxl']=resizeLow
resizePresets['s=78/800^.jxl']=resizeSmall
resizeIdentity=(
	quality=92
	size=100%
	dst=.jxl
)
resizeHalf=(
	predicate=1000+
	quality=90
	size=50%
	dst=.jpg
)
resizeMid=(
	predicate=1000+
	quality=85
	size=50%
	dst=.jxl
)
resizeQuarter=(
	predicate=2000+
	quality=85
	size=25%
	dst=.jxl
)
resizeLow=(
	predicate=1800+
	quality=82
	size=1280
	dst=.jxl
)
resizeSmall=(
	predicate=1200+
	quality=78
	size=800^
	dst=.jxl
)

resizeConfig=(
	predicate=2000+
	quality=92
	dst=.jxl
)

downloadConfig=(metadata=false)
editConfig=(
	--rename
	no-metadata
	volume=-14LUFS
	volumeTolerance=0.4
)

linkFixConfig=(--resources ~/Music/Songs/)
renameConfig+=(+D)
