declare -gA resizePresets
resizePresets['i=92/1.jxl']=resizeIdentity
resizePresets['h=90/2.jpg']=resizeHalf
resizePresets['m=85/2.jxl']=resizeMid
resizePresets['q=85/4.jpg']=resizeQuarter
resizePresets['s=80/1280.jxl']=resizeSmall
resizePresets['l=78/800^.jxl']=resizeLow
resizePresets['e=90/1.jpg']=resizeExport
resizeIdentity=(
	quality=92
	size=100%
	dst=.jxl
)
resizeHalf=(
	predicate=1000+
	quality=90
	size=50%
	dst=.jpg
)
resizeMid=(
	predicate=1000+
	quality=85
	size=50%
	dst=.jxl
)
resizeQuarter=(
	predicate=2000+
	quality=85
	size=25%
	dst=.jpg
)
resizeSmall=(
	predicate=1800+
	quality=80
	size=1280
	dst=.jxl
)
resizeLow=(
	predicate=1200+
	quality=78
	size=800^
	dst=.jxl
)
resizeExport=(
	quality=90
	size=100%
	dst=.jpg
)

resizeConfig=(
	predicate=2000+
	quality=90
	dst=.jxl
)

downloadConfig=(metadata=false)
editConfig=(
	rename=true
	metadata=false
	volume=-14LUFS
	volumeTolerance=0.4
	dst=.opus
)
cutConfig=(
	rename=true
)

linkFixConfig=(--resources ~/Music/Songs/)
renameConfig+=(+D)
