#!/usr/bin/bash
# Backlight detection
if [[ $button && $button != 2 ]]; then
	((button == 1 || button == 4)) && backlight + 10 > /dev/null || backlight - 10 > /dev/null
fi

light=$(backlight)
TEXT=" $light%"

echo "$TEXT
$TEXT"
~/.config/i3blocks/colorcode $light
