#!/usr/bin/bash
read -a line <<< "$(acpi)"
TEXT=${line[2]:0:1}
STATE=${line[3]%\%*}
TIME=${line[4]%:??}

if [[ -z $TEXT ]]; then
	echo 
elif [[ ${line[6]} == zero ]]; then
	echo " $STATE%"
else
	case "$TEXT" in
		'D')
			if ((STATE <= 20)); then
				TEXT=
				if ((STATE > 17)); then
					notify-send -t 0 -u low -h int:value:$STATE \
						-h string:synchronous:battery "Battery   $STATE%" 'Plug the system in.'
				elif ((STATE > 14)); then
					notify-send -u critical -h int:value:$STATE \
						-h string:synchronous:battery "Battery   $STATE%" 'Plug the system in.'
					case "$(rofi -dmenu -l 3 -p "  $STATE%" <<< 'Suspend
Hibernate
Power off')" in
						'Suspend') systemctl suspend ;;
						'Hibernate') { [[ $(swapon --show=NAME) ]] || sudo swapon /swapfile; } &&
							systemctl hibernate && sleep 60 && sudo swapoff /swapfile ;;
						'Power off') systemctl poweroff ;;
					esac
				else
					{ [[ $(swapon --show=NAME) ]] || sudo swapon /swapfile; } && systemctl \
						hibernate && sleep 60 && sudo swapoff /swapfile
				fi
				echo "$TEXT $STATE% $TIME"
				exit 33
			elif ((STATE < 40)); then
				TEXT=
			elif ((STATE < 60)); then
				TEXT=
			elif ((STATE < 80)); then
				TEXT=
			else
				TEXT=
			fi
			;;
		'C') TEXT= ;;
		'F') TEXT= ;;
		*) TEXT= ;;
	esac
	echo "$TEXT $STATE% $TIME"
fi
