#!/usr/bin/bash
bat=(/sys/class/power_supply/BAT*/uevent)
eval "$(sed 's/^.\{13\}//' "${bat[${BAT:-0}]}")"
if [[ -z $STATUS || $POWER_NOW -lt 1000000 ]]; then
	echo " $CAPACITY%"
else
	((TIME = ENERGY_NOW * 60 / POWER_NOW))
	((M = TIME % 60))
	((M < 10)) && M=0$M
	TIME="$((TIME / 60)):$M"
	case "$STATUS" in
		D*)
			USAGE=$((POWER_NOW / 100000))
			if ((CAPACITY > 40)); then
				((CAPACITY > 80)) && TEXT= || { ((CAPACITY > 60)) && TEXT= || TEXT=; }
			elif ((CAPACITY > 25)); then
				TEXT=
			elif ((CAPACITY > 20)); then
				TEXT=
				bad=1
				notify-send -u low -h int:value:$CAPACITY \
					-h string:synchronous:battery "Battery   $CAPACITY%" 'Plug the system in.'
			else
				{ [[ $(swapon --show=NAME) ]] || sudo swapon /swapfile; } &&
					systemctl hibernate && sleep 60 &&
					sudo swapoff /swapfile && swaymsg output eDP-1 power on
			fi
			;;
		C*)
			TEXT= USAGE=$((POWER_NOW / 100000))
			((CAPACITY >= 80)) && bad=1
			;;
		F*) TEXT= ;;
		*) TEXT= ;;
	esac
	echo "$TEXT $CAPACITY%${USAGE:+/$((USAGE / 10)).${USAGE:0-1}W} $TIME"
	[[ -z $bad ]] || exit 33
fi
