#!/usr/bin/bash

bat=(/sys/class/power_supply/BAT*)

charge_limit() {
	local CHECK_FILE=/tmp/my/conservative_bat_manual
	if [[ $2 == auto* ]]; then
		# not overriding user decission or when system is already charged
		[[ -f $CHECK_FILE || $(<"$bat/power_now") == 0 ]] && return 0
	else
		touch "$CHECK_FILE"
	fi

	# alt path: /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode
	local file=(/sys/class/power_supply/*/extensions/*/conservation_mode)
	declare -i now=$(<"$file")
	local new
	case "$1" in
		'toggle' | 'tgl' | '') ((new = (now + 1) % 2)) ;;
		'conservative' | 'limit' | 80) new=1 ;;
		'full' | 100) new=0 ;;
	esac

	((new)) && local args=(-u normal '60% Max Charge') || local args=(-u critical 'Full Charge')
	if ((now == new)); then
		[[ $2 == auto* ]] && return 0
		args+=('(Already active)')
	else
		echo "$new" | sudo tee "$file" >/dev/null
	fi
	notify-send -t 1000 "${args[@]}"
}

if [[ $1 ]]; then
	charge_limit "$@"
	exit 0
elif [[ $button == 3 ]]; then
	charge_limit toggle manual
fi

read STATUS <"$bat/status"
read ENERGY_NOW <"$bat/energy_now"
read POWER_NOW <"$bat/power_now"
read CAPACITY <"$bat/capacity"

if [[ -z $STATUS || $POWER_NOW -lt 1000000 ]]; then # when charging at 0 rate = conservation mode
	echo " $CAPACITY%"
else
	((TIME = ENERGY_NOW * 60 / POWER_NOW))
	((M = TIME % 60))
	((M < 10)) && M=0$M
	TIME="$((TIME / 60)):$M"
	case "$STATUS" in
		D*)
			USAGE=$((POWER_NOW / 100000)) # units: 100 mW
			if ((CAPACITY > 40)); then
				if ((CAPACITY > 80)); then
					TEXT=
				else
					((CAPACITY > 60)) && TEXT= || TEXT=
				fi
			elif ((CAPACITY > 25)); then
				TEXT=
			elif ((CAPACITY > 20)); then
				TEXT=
				bad=1
				notify-send -u low -h int:value:$CAPACITY \
					-h string:synchronous:battery "Battery   $CAPACITY%" 'Plug the system in.'
			else
				bash hibernateDelayed.sh &
				disown
			fi
			;;
		C*)
			TEXT=
			USAGE=$((POWER_NOW / 100000)) # units: 100 mW
			if ((CAPACITY >= 80)); then
				charge_limit conservative auto
				bad=1
			elif ((CAPACITY >= 55 && CAPACITY <= 56 && USAGE > 10)); then
				charge_limit full auto
			fi
			;;
		F*)
			TEXT=
			rm /tmp/my/conservative_bat_manual &>/dev/null
			charge_limit conservative auto
			;;
		*) TEXT= ;;
	esac
	echo "$TEXT $CAPACITY%${USAGE:+/$((USAGE / 10)).${USAGE:0-1}W} $TIME"
	[[ -z $bad ]] || exit 33
fi
