#!/usr/bin/bash

setTheme() {
	gsettings set org.gnome.desktop.interface color-scheme prefer-${1,,}
	gsettings set org.gnome.desktop.interface gtk-theme ${1^}
	sed "s/Dark/${1^}/" ~/.config/gtk-3.0/theme.ini >/tmp/my/gtk3rc
	sed '1d;s/=\([a-z].*\|[A-Z][^A-Z].*\)/="\1"/' /tmp/my/gtk3rc >/tmp/my/gtk2rc
	ln -sf ~/.config/qt6ct/colors/$1.conf /tmp/my/qt
	ln -sf ~/.config/rofi/$1.rasi /tmp/my/rofi
	ln -sf ~/.config/foot/$1.ini /tmp/my/foot

	# toggle theme for foot terminal linked to /bin/xterm
	local signal
	[[ $1 == dark ]] && signal=SIGUSR1 || signal=SIGUSR2
	pkill --signal $signal xterm

	local msg="\x94\x0\x1\xafnvim_set_option\x92\xaabackground\xa${#1}$1"

	for f in /run/user/$(id -u)/nvim.*.0; do
		local pid=${f#*.}
		ps -p ${pid%.*} >/dev/null && printf "$msg" | ncat -U "$f"
	done
}

updateTheme() {
	pkill -RTMIN+20 i3blocks
	if ((STAT[0] <= x && x < STAT[1])); then
		[[ ! -e /tmp/my/day || $next == 0 ]] && touch /tmp/my/day && setTheme light
		swaymsg -q 'set $bg #ffffff; set $fg #000000'
		next=${STAT[1]}
	else
		[[ $next == 0 ]] || rm /tmp/my/day &>/dev/null && setTheme dark
		swaymsg -q 'set $bg #101010; set $fg #ffffff'
		((x > STAT[1])) && next=1440 || next=${STAT[0]}
	fi
	swaymsg -q "$(grep 'colors {' -A 10 ~/.config/sway/20_layout.swayconf |
		grep '\$' -B 10 | sed '1d;/^\s*#/d;s/^/bar bar-0 colors/')"
	prev=$x
}

if [[ $1 ]]; then
	STAT=(0 1)
	[[ $1 == light || ($1 == toggle && ! -e /tmp/my/day) ]] && x=0 || x=1
	updateTheme
	exit 0
fi

STAT=($(sunwait list 47.8N 13E | sed 's/:/ /g;s/,//' | awk '{print($1*60+$2,$3*60+$4)}'))
next=0

update() {
	x=($(date +"%H %M %S"))
	echo " ${x[0]}:${x[1]}"
	((x[0] = ${x[0]#0} * 60 + ${x[1]#0}))
}

while :; do
	update
	((next < x || x < prev)) && updateTheme >/dev/null
	sleep $((60 - ${x[2]#0}))
done
