#!/usr/bin/bash
# CPU temperature script

temp=$(cat /sys/class/thermal/thermal_zone0/temp)
temp=${temp%000}

if ((temp < 45)); then
	TEXT=" <b>$temp°C</b>"
elif ((temp < 60)); then
	TEXT=" <b>$temp°C</b>"
elif ((temp < 75)); then
	TEXT=" <b>$temp°C</b>"
elif ((temp < 90)); then
	TEXT=" <b>$temp°C</b>"
else
	TEXT=" <b>$temp°C</b>"
fi

echo "$TEXT
$TEXT"
# temp-30 because lowest temp is practically 30° C
~/.config/i3blocks/colorcode $((100 - (temp - 30) * 10 / 7))
