#!/usr/bin/bash
#Memory usage, total mem usage on click

[[ $BLOCK_INSTANCE == swap && -z $(swapon --show=NAME) ]] && exit 0
declare -i MTotal MUsed STotal SUsed
while read -ra line; do
	case ${line[0]} in
		'Mem:')
			MTotal=${line[1]}
			MUsed=${line[2]}+${line[4]}
			;;
		'Swap:')
			STotal=${line[1]}
			SUsed=${line[2]}
			break
			;;
	esac
done <<< "$(free -m)"

if [[ $BLOCK_INSTANCE == swap ]]; then
	USED=$SUsed
	TOTAL=$(bc <<< "scale=1;$STotal/1024")
	PCT=$(bc <<< "scale=1;$SUsed/$STotal*100")
	((MUsed * 100 / MTotal < 70)) && sudo swapoff /swapfile
else
	USED=$MUsed
	TOTAL=$(bc <<< "scale=1;$MTotal/1024")
	PCT=$(bc <<< "scale=1;$MUsed*100/$MTotal")
	((MUsed * 100 / MTotal >= 90)) && [[ -z $(swapon --show=NAME) ]] && sudo swapon /swapfile
fi

TOTAL=${TOTAL/#./0.}
PCT=${PCT/#./0.}

((USED < 999)) && TYPE="G" && USED=$(bc <<< "scale=1;$USED/1024") &&
	USED=${USED/#./0.} || TYPE="M"

# Nice icons:  
if ((button == 1)); then
	TEXT=" $USED$TYPE/${TOTAL}G ($PCT%)"
elif [[ $button == 3 ]]; then
	ps axo rss,comm |
		awk '{ proc_list[$2]++; proc_list[$2 "," 1] += $1; } \
                END { for (proc in proc_list) { printf("%d\t%s\n", \
                proc_list[proc "," 1],proc); }}' | sort -n | tail -n 10 | sort -rn |
		awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' |
		rofi -dmenu -location 3 -p ramuse >> /dev/null
	TEXT="<b> $PCT%</b>"
else
	TEXT="<b> $PCT%</b>"
fi
echo "$TEXT
$TEXT"
~/.config/i3blocks/colorcode $((100 - ${PCT/.*/}))
