#!/usr/bin/bash
# Volume script
#Nice icons:       
read -ra WP < /tmp/wp
if [[ $button ]]; then
	if ((button > 3)); then
		wpctl set-volume ${WP[1]} 1%$( ((button == 4)) && echo + || echo -)
	elif ((button == 1)); then
		wpctl set-mute ${WP[1]} toggle
	else
		xterm -e pulsemixer &
		disown
	fi
fi

read -ra ARR <<< "$(wpctl get-volume ${WP[1]})"
VOL=${ARR[1]/./}
VOL=${VOL##0}
MUTED=${ARR[2]}

if [[ -z $VOL ]]; then
	printf " ?\n ?\n"
	~/.config/i3blocks/colorcode \?
	exit 0
fi

if [[ $MUTED ]]; then
	ICON=
else
	ICON=
fi

TEXT="$ICON $VOL%"
notify-send -a signal -h int:value:$VOL -h string:synchronous:mic "$TEXT"
echo "$TEXT
$TEXT"
[[ $MUTED ]] && echo "#f03522" || ~/.config/i3blocks/colorcode $((VOL * 2))
