#!/usr/bin/env bash
#Signal managing script for statusbar

case "$1" in
	"vol")
		if [[ $2 == toggle ]]; then
			pactl set-sink-mute 0 $2
		else
			pactl set-sink-volume 0 $2%
		fi
		pkill -RTMIN+10 i3blocks
		;;
	"mic")
		if [[ $2 == toggle ]]; then
			pactl set-source-mute 0 $2
		else
			pactl set-source-volume 0 $2%
		fi
		pkill -RTMIN+13 i3blocks
		;;
	"light")
		light=$(backlight $2 $3)
		notify-send -a signal -h int:value:$light -h string:synchronous:light " $light%"
		pkill -RTMIN+11 i3blocks
		;;
	"kb")
		[[ $(swaymsg -t get_inputs -p | grep US -m 1) ]] && kb=cz || kb=us
		swaymsg input "1:1:AT_Translated_Set_2_keyboard" xkb_switch_layout next
		notify-send -a signal -h string:synchronous:kb " $kb"
		pkill -RTMIN+12 i3blocks
		;;
esac
