#!/usr/bin/env bash
# Checks for system updates, requires pacman-contrib installed

if ((button == 1)); then
	~/.config/i3/term -e paru --noconfirm -Syu &> /dev/null && break
	declare -i count=0
elif ((button == 3)); then
	update=$(checkupdates | awk '{print $1}' | rofi -dmenu -p 'update')
	if [[ $update ]]; then
		~/.config/i3/term -e paru --noconfirm -Sy $update &> /dev/null && break
	fi
fi
if [[ -z $count ]]; then
	[[ "$(uptime)" == *" 0 min, "* ]] && sleep 10
	declare -i count=0
	while read line; do
		[[ $line ]] && count+=1
	done <<< $(checkupdates)
fi

TEXT=" <b>$count</b>"
printf '%s\n%s\n' "$TEXT" "$TEXT"
~/.config/i3blocks/colorcode $((100 + count * 2))
((count >= 50)) && exit 33 || exit 0
