#!/usr/bin/bash
# Checks for system updates, requires pacman-contrib installed

if ((button == 1)); then
	xterm -e paru -Syu &> /dev/null && exit 0
elif ((button == 3)); then
	update=$(checkupdates | awk '{print $1}' | rofi -dmenu -p 'update')
	[[ $update ]] && xterm -e paru -Sy $update &> /dev/null && exit 0
fi

[[ "$(uptime)" =~ ' 0 min,' ]] && sleep 10
declare -i count=0
while read -r line; do
	[[ ${line%% *} == linux* ]] && update=1
	[[ $line ]] && count+=1
done <<< "$(checkupdates)"

if [[ $update ]]; then
	TEXT=" <b>$count</b>"
	echo "$TEXT
$TEXT"
	exit 33
fi
