#!/usr/bin/bash
# Volume script
#Nice icons:       
read -ra WP < /tmp/wp
if [[ $button ]]; then
	if ((button > 3)); then
		wpctl set-volume ${WP[0]} 10%$( ((button == 4)) && echo + || echo -)
	elif ((button == 1)); then
		wpctl set-mute ${WP[0]} toggle
	else
		xterm -e pulsemixer &
		disown
	fi
fi

read -ra ARR <<< "$(wpctl get-volume ${WP[0]})"
VOL=${ARR[1]/./}
VOL=${VOL##0}
MUTED=${ARR[2]}

if [[ -z $VOL ]]; then
	printf " ?\n ?\n"
	~/.config/i3blocks/colorcode \?
	exit 0
fi

if [[ $MUTED ]]; then
	ICON=
elif ((VOL >= 70)); then
	ICON=
elif ((VOL >= 30)); then
	ICON=
else
	ICON=
fi

notify-send -a signal -h int:value:$VOL -h string:synchronous:volume "$ICON $VOL"
echo "$ICON $VOL%
$ICON $VOL%"
[[ $MUTED ]] && echo "#f03522" || ~/.config/i3blocks/colorcode $VOL
