#!/usr/bin/bash
((button == 1)) && xterm -e nmtui &> /dev/null

if [[ $BLOCK_INSTANCE ]]; then
	read -ra line <<< "$(ip a s "$BLOCK_INSTANCE")"
else
	while read -ra line; do
		[[ ${line[1]} =~ ^wlo || ${line[1]} =~ ^wlp ]] && BLOCK_INSTANCE=${line[1]} && break
	done <<< "$(ip a)"
fi
[[ ${line[2]} =~ UP ]] && on=1
declare -i quality
if [[ $on ]]; then
	while read -ra line; do
		[[ ${line[0]} == "$BLOCK_INSTANCE"* ]] &&
			quality=$((${line[2]%.*} * 10 / 7)) && break
	done < /proc/net/wireless
	[[ $quality ]] && read -ra line <<< "$(nmcli)" && ssid=${line[-1]}
fi
if [[ $on ]]; then
	if [[ $quality ]]; then
		echo " $quality%: $ssid"
	else
		echo 
		exit 33
	fi
else
	echo 
fi
