#!/usr/bin/env bash
# Internet status script

#Nice icons:    
if [[ $button -eq 1 ]]; then
	i3 exec -- st -e nmtui &> /dev/null
fi

if [[ $BLOCK_INSTANCE ]]; then
	read -a line <<< $(ip a s $BLOCK_INSTANCE)
else
	while read -a line; do
		[[ ${line[1]} == wlp* ]] && break
	done <<< $(ip a)
	BLOCK_INSTANCE=wlp
fi
[[ ${line[2]} == *UP* ]] && on=1
if [[ $on ]]; then
	while read -a line; do
		[[ ${line[0]} == "$BLOCK_INSTANCE"* ]] &&
			quality=$((${line[2]%.*} * 10 / 7)) && break
	done < /proc/net/wireless
	[[ $quality ]] && read -a line <<< $(nmcli) && ssid=${line[-1]}
fi
TEXT=$([[ $on ]] && ([[ $quality ]] && echo " $quality%: $ssid" || echo "") || echo "")

echo "$TEXT"
echo "$TEXT"
~/.config/i3blocks/colorcode $([[ -z "$quality" && "$on" ]] && echo 0 || echo $quality)
